### ISSUE TITLE
Search input does not have a label

### ISSUE THREAD

**Issue by ashleypeacock** [melissaegg/trauma-informed-design-resources#4]
### Issue

Search does not contain a label. Placeholders are one approaches to resolving 'Label in name' in some contexts; but as a sole use it impacts people with anxiety and cognitive needs.

<img width="527" alt="image" src="https://github.com/user-attachments/assets/b756c61c-9f25-4be6-befc-5490993d78ac">

<img width="722" alt="image" src="https://github.com/user-attachments/assets/5c25277f-b81f-4981-bcbc-b7bf3e744897">

### Recommendations:
* Add `label` element and use for to connect it to the `searchbox`.

References
* [Label In Name](https://www.w3.org/WAI/WCAG21/Understanding/label-in-name.html)
* [Labels or Instructions](https://www.w3.org/TR/UNDERSTANDING-WCAG20/minimize-error-cues.html)

**Comment by melissaegg** [comment]
Fixed! Thank you as placeholder text is crappy in search boxes anyway so this was a two-for-one fix.

**Comment by melissaegg** [comment]
Fixed! Thank you as placeholder text is crappy in search boxes anyway so this was a two-for-one fix.
