### ISSUE TITLE
Link Purpose

### ISSUE THREAD

**Issue by ashleypeacock** [melissaegg/trauma-informed-design-resources#6]
### Issue

Ensure other links describe the purpose (e.g opening new page or going to youtube).

<img width="201" alt="image" src="https://github.com/user-attachments/assets/b29e5844-a5f8-43ba-9d24-3d94ad24f33c">

### Recommendations
* [Add details about the purpose and direction of links](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-refs.html). This will support decision-making for people using assistive tech 

### Resources
[Link Purpose](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-refs.html
)

**Comment by melissaegg** [comment]
Yes, unfortunately, plenty of resources are not accessible. For example, I've asked the publisher of an article I wrote to make it accessible and he didn't know what I was talking about. So I just provide it via Word if asked. (Not ideal).

I'm not sure I can change this without more coding skills as this has to do with the Excel spreadsheet links.

**Comment by ashleypeacock** [comment]
Apologies; I combined two issues into one and didn't explain properly; pre-holiday brain! I've updated the original issue.

The main issue here is that links should indicate to users they open in new windows. Generally, links opening in new windows are a bit disorientating for screen-reader users. So a visual indication of opening in a new window and a means for assistive tech to perceive it is ideal. 

For example:

`<a href="help.html" target="_blank">Show Help (opens new window)</a>
`
[Source](https://www.w3.org/TR/WCAG20-TECHS/H83.html)

Although this wouldn't fit the design very well, here's another:

```
<a href="http://article" target="_blank">
<i class="fas fa-external-link-alt" aria-hidden="true"></i> <!-- visual indication link opens new window-->
<span class="screen-reader-text"> opens a new window</span></a> <!-- hidden from view but available to screen readers -->
```
[This](https://theadminbar.com/accessibility-weekly/opening-links-in-new-tabs-or-not/) is a fairly good explanation incase of interest. 

But for ease I can submit a pull-request, then you can review for the design aspect :)
