### ISSUE TITLE
Text spacing: content using ellipsis without an open to expand

### ISSUE THREAD

**Issue by ashleypeacock** [melissaegg/trauma-informed-design-resources#7]
### Issues
Content uses ellipsis without providing options to expand and read. 

<img width="299" alt="image" src="https://github.com/user-attachments/assets/7724136c-9aac-4713-8040-8de7629d6b2f">

### Recommendations

* [Text spacing](https://www.w3.org/WAI/WCAG21/Understanding/text-spacing.html)

**Use of ellipses**
There may be regions of a page where text containers cannot expand due to design constraints (such as a maximum width for the left navigation or table column headers). A common convention if text exceeds its space is to replace truncated text with an ellipsis. Where ellipses appear as a result of modifying text style properties, the page can still meet the Text Spacing requirements, so long as the content is still available. For example:

a mechanism is provided to reveal the truncated text on the page (for instance, the text appears on focus or on activation)
where the ellipsis is part of a section of content which includes a link, the truncated text is revealed on the linked page
Where text is not truncated but it is when text is spaced, if there is no mechanism to show the truncated text, it fails this Success Criterion.

**Comment by melissaegg** [comment]
I got rid of the ellipses altogether, as we didn't like them anyway. The description is not actually the first part of a sentence so it was confusing anyway. Fixed.
